/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author G50
 */
public class Esettings extends javax.swing.JPanel {

    /**
     * Creates new form session_reporting
     */
    int x = 0;
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;
    String theReg;

    public Esettings() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        Properties properties = new Properties();
        try {
             InputStream inputStream = Esettings.class.getResourceAsStream("/store/mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);

        }

        try {
            String dbname = properties.getProperty("db.name");
            String pass = properties.getProperty("db.pass");
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + properties.getProperty("db.host") + ":" + properties.getProperty("db.port") + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);
        } catch (Exception e) {

            System.exit(0);
        }

        try {
            String sql2 = "SELECT * FROM staff ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);

            while (rs.next()) {
                String username = rs.getString("user_name");
                if (username.equals(PharmacyMenu.theUser)) {
                    empID.setText(rs.getString("emp_id"));
                    fName.setText(rs.getString("firstName"));
                    oName.setText(rs.getString("otherNames"));
                    gender.setSelectedItem(rs.getString("gender"));
                    phone.setText(rs.getString("phone"));
                    mail.setText(rs.getString("email"));
                    dept.setSelectedItem(rs.getString("dept"));
                    break;
                }
            }
             String sql22 = "SELECT * FROM users ";
            st = con.createStatement();
            rs = st.executeQuery(sql22);

            while (rs.next()) {
                String username = rs.getString("user_name");
                if (username.equals(PharmacyMenu.theUser)) {
                    uName.setText(username);
                    pWord.setText(rs.getString("pass_word"));                
                    break;
                }
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        empID = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        oName = new javax.swing.JTextField();
        bl2 = new javax.swing.JLabel();
        bl1 = new javax.swing.JLabel();
        uL11 = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        pWord = new javax.swing.JTextField();
        bl4 = new javax.swing.JLabel();
        bl5 = new javax.swing.JLabel();
        lB11 = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<String>();
        bl3 = new javax.swing.JLabel();
        bl6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        bl7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        dept = new javax.swing.JComboBox<String>();
        bl8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "     Settings     ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empID.setEditable(false);
        empID.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        empID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(empID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 310, -1));

        fName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        fName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 310, 30));

        oName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        oName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(oName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 310, 30));

        bl2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl2.setText("gender");
        jPanel3.add(bl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 130, 40));

        bl1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl1.setText("first Name");
        jPanel3.add(bl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 90, 30));

        uL11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL11.setText("employee ID");
        jPanel3.add(uL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 140, 20));

        uName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(uName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 310, 30));

        pWord.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        pWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(pWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 310, 30));

        bl4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl4.setText("pass Word");
        jPanel3.add(bl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 100, 30));

        bl5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl5.setText("user Name");
        jPanel3.add(bl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 100, 30));

        lB11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB11.setText("Update");
        lB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB11ActionPerformed(evt);
            }
        });
        jPanel3.add(lB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 250, -1));

        gender.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 310, -1));

        bl3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl3.setText("other Names");
        jPanel3.add(bl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 130, 30));

        bl6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl6.setText("phone Number");
        jPanel3.add(bl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 130, 30));

        phone.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 310, 30));

        bl7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl7.setText("email");
        jPanel3.add(bl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 130, 30));

        mail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 310, 30));

        dept.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        dept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reception", "Laboratory", "Doctors Station", "Clinic", "Pharmacy", "System Administration", " " }));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });
        jPanel3.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 310, -1));

        bl8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        bl8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bl8.setText("department");
        jPanel3.add(bl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed

    private void lB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB11ActionPerformed
        if (fName.getText().equals("") || oName.getText().equals("") || phone.getText().equals("") || mail.getText().equals("") || uName.getText().equals("") || pWord.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Kindly fill all fields", "Alert", 1);
        } else {
            try {

                String sql = "Update staff set user_name='" + uName.getText() +"',firstName='" + fName.getText() + "',otherNames='" + oName.getText() + "',gender='" + (String) gender.getSelectedItem() + "',phone='" + phone.getText() + "',email='" + mail.getText() + "',dept='" + (String) dept.getSelectedItem() + "' where user_name='" + PharmacyMenu.theUser + "'";
                pst = con.prepareStatement(sql);
                pst.executeUpdate();
                String sql2 = "Update users set pass_word='" + pWord.getText() + "' where user_name='" + uName.getText() + "'";
                pst = con.prepareStatement(sql2);
                pst.executeUpdate();
                PharmacyMenu.theUser=uName.getText();

                JOptionPane.showMessageDialog(this, "Update Succesful", "Alert", 1);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Alert", 1);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lB11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bl1;
    private javax.swing.JLabel bl2;
    private javax.swing.JLabel bl3;
    private javax.swing.JLabel bl4;
    private javax.swing.JLabel bl5;
    private javax.swing.JLabel bl6;
    private javax.swing.JLabel bl7;
    private javax.swing.JLabel bl8;
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JTextField empID;
    private javax.swing.JTextField fName;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton lB11;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField oName;
    private javax.swing.JTextField pWord;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel uL11;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables
}
