/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author G50
 */
public class logIn extends javax.swing.JFrame {

    /**
     * Creates new form animeFrame
     */
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;

    public logIn() {
        initComponents();
        ImageIcon img = new ImageIcon(getClass().getResource("/store/326.png"));
        this.setIconImage(img.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        l2 = new javax.swing.JPasswordField();
        d4 = new javax.swing.JButton();
        d22 = new javax.swing.JLabel();
        l1 = new javax.swing.JTextField();
        d11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medical Information Management System - Login Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(620, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setBackground(java.awt.SystemColor.controlDkShadow);
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLayeredPane1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 310, 30));

        d4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d4.setText("Log In");
        d4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 220, 31));

        d22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d22.setText("password");
        d22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.add(d22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 220, -1));

        l1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 310, 30));

        d11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d11.setText("username");
        d11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/log_bk.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Properties properties = new Properties();
        try {
              InputStream inputStream = logIn.class.getResourceAsStream("/store/mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);

        }

        try {
            String dbname = properties.getProperty("db.name");
            String pass = properties.getProperty("db.pass");
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + properties.getProperty("db.host") + ":" + properties.getProperty("db.port") + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);
        } catch (Exception e) {

            System.exit(0);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        String userName = l1.getText();
        String passWord = l2.getText();
        String userN = "";
        int xp = 1;
        if (l1.getText().equals("") || l2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please provide the username and password", "Alert", 1);

        } else {
            try {
                String sql2 = "SELECT * FROM users ";
                st = con.createStatement();
                rs = st.executeQuery(sql2);
                while (rs.next()) {
                    userN = rs.getString("user_name");
                    String passW = rs.getString("pass_word");
                    if (userN.equals(userName) && passW.equals(passWord)) {
                        xp = 3;
                        break;
                    }

                }

            } catch (Exception e) {

            }
            if (xp == 1) {
                JOptionPane.showMessageDialog(this, "Wrong username or password Combination", "Alert", 1);
            } else {

                try {
                    String sql21 = "SELECT dept,firstName,otherNames FROM staff WHERE user_name='" + userN + "' ";
                    st = con.createStatement();
                    rs = st.executeQuery(sql21);
                    String dept = "";
                    String firstName = "";
                    String otherNames = "";
                    while (rs.next()) {
                        dept = rs.getString("dept");
                        firstName = rs.getString("firstName");
                        otherNames = rs.getString("otherNames");
                        break;
                    }

                    if (dept.equalsIgnoreCase("Reception")) {
                        ReceptionMenu vbn = new ReceptionMenu();
                        vbn.names = firstName + " " + otherNames;
                        vbn.theUser = userN;
                        this.dispose();
                        vbn.setVisible(true);

                    }else if (dept.equalsIgnoreCase("Doctors Station")) {
                        DoctorMenu vbn = new DoctorMenu();
                        vbn.names = firstName + " " + otherNames;
                        vbn.theUser = userN;
                        this.dispose();
                        vbn.setVisible(true);

                    }else if(dept.equalsIgnoreCase("Laboratory")){
                         LabMenu vbn = new LabMenu();
                        vbn.names = firstName + " " + otherNames;
                        vbn.theUser = userN;
                        this.dispose();
                        vbn.setVisible(true);
                    }else if(dept.equalsIgnoreCase("Clinic")){
                         ClinicMenu vbn = new ClinicMenu();
                        vbn.names = firstName + " " + otherNames;
                        vbn.theUser = userN;
                        this.dispose();
                        vbn.setVisible(true);
                    }else if(dept.equalsIgnoreCase("Pharmacy")){
                         PharmacyMenu vbn = new PharmacyMenu();
                        vbn.names = firstName + " " + otherNames;
                        vbn.theUser = userN;
                        this.dispose();
                        vbn.setVisible(true);
                    }
                    
                    
                } catch (Exception e) {
                }

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_d4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d22;
    private javax.swing.JButton d4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField l1;
    private javax.swing.JPasswordField l2;
    // End of variables declaration//GEN-END:variables
}
