/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author G50
 */
public class manage_students extends javax.swing.JPanel {

    /**
     * Creates new form session_reporting
     */
    int x = 0;
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;
    String theReg;

    String filename="";

    public manage_students() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        Properties properties = new Properties();
        try {
              InputStream inputStream = manage_students.class.getResourceAsStream("/store/mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);

        }

        try {
            String dbname = properties.getProperty("db.name");
            String pass = properties.getProperty("db.pass");
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + properties.getProperty("db.host") + ":" + properties.getProperty("db.port") + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);
        } catch (Exception e) {

            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uL11 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        uL12 = new javax.swing.JLabel();
        otherNames = new javax.swing.JTextField();
        uL13 = new javax.swing.JLabel();
        idNumber = new javax.swing.JTextField();
        uL15 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<String>();
        uL14 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        uL5 = new javax.swing.JLabel();
        lB6 = new javax.swing.JButton();
        regNo = new javax.swing.JTextField();
        uL10 = new javax.swing.JLabel();
        lB8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        uL9 = new javax.swing.JLabel();
        phoneNo = new javax.swing.JTextField();
        uL16 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        uL8 = new javax.swing.JLabel();
        uL17 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox<String>();
        course = new javax.swing.JTextField();
        doa = new javax.swing.JTextField();
        uL18 = new javax.swing.JLabel();
        lB9 = new javax.swing.JButton();
        lB10 = new javax.swing.JButton();
        lB11 = new javax.swing.JButton();
        lB12 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "     Manage Students    ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL11.setText("First Name");
        jPanel2.add(uL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 20));

        fName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        fName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        uL12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL12.setText("Other Names");
        jPanel2.add(uL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 20));

        otherNames.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        otherNames.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        otherNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNamesActionPerformed(evt);
            }
        });
        jPanel2.add(otherNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, -1));

        uL13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL13.setText("Id Number");
        jPanel2.add(uL13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 20));

        idNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        idNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(idNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, -1));

        uL15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL15.setText("Gender");
        jPanel2.add(uL15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 20));

        gender.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 250, -1));

        uL14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL14.setText("Date of Birth");
        jPanel2.add(uL14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 20));

        dob.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dob.setText("e.g 27/9/2017");
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobKeyTyped(evt);
            }
        });
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 30));

        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png"))); // NOI18N
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 140, 150));

        uL5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uL5.setText("Passport");
        jPanel2.add(uL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, -1));

        lB6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB6.setText("Load");
        lB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB6ActionPerformed(evt);
            }
        });
        jPanel2.add(lB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 120, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 480, 340));

        regNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        regNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNoActionPerformed(evt);
            }
        });
        jPanel3.add(regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, -1));

        uL10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL10.setText("Registration Number");
        jPanel3.add(uL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 20));

        lB8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB8.setText("Fetch >>>");
        lB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB8ActionPerformed(evt);
            }
        });
        jPanel3.add(lB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 110, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL9.setText("Phone No.");
        jPanel4.add(uL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));

        phoneNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        phoneNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNo.setText("e.g 0705 187 937");
        phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoActionPerformed(evt);
            }
        });
        phoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNoKeyTyped(evt);
            }
        });
        jPanel4.add(phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 320, 30));

        uL16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL16.setText("Mail");
        jPanel4.add(uL16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, -1));

        mail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mail.setText("e.g Test@gmail.com");
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailKeyTyped(evt);
            }
        });
        jPanel4.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 320, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 480, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL8.setText("Course");
        jPanel5.add(uL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        uL17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL17.setText("Faculty/School");
        jPanel5.add(uL17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        faculty.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        faculty.setMaximumRowCount(4);
        faculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School of Business & Economics", "Agriculture & Natural Resource Management", "Information Science & Technology", "School of Law", "Education & Human Resource Dev.", "Health Sciences", "Faculty of Pure and Applied Sciences", "Arts & Social Sciences" }));
        jPanel5.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 340, 30));

        course.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        course.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 340, -1));

        doa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        doa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        doa.setText("e.g 27/9/2017");
        doa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doaActionPerformed(evt);
            }
        });
        doa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doaKeyTyped(evt);
            }
        });
        jPanel5.add(doa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 340, 30));

        uL18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL18.setText("Admission Date");
        jPanel5.add(uL18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 510, 190));

        lB9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB9.setText("UPDATE");
        lB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB9ActionPerformed(evt);
            }
        });
        jPanel3.add(lB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 130, 30));

        lB10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB10.setText("DELETE");
        lB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB10ActionPerformed(evt);
            }
        });
        jPanel3.add(lB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 150, 30));

        lB11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB11.setText("SAVE");
        lB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB11ActionPerformed(evt);
            }
        });
        jPanel3.add(lB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 130, 30));

        lB12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB12.setText("CLEAR FIELDS");
        lB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB12ActionPerformed(evt);
            }
        });
        jPanel3.add(lB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB6ActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int rase = chooser.showOpenDialog(this);

        if (rase == JFileChooser.APPROVE_OPTION) {

            FileInputStream fis = null;

            File file = chooser.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getAbsolutePath());
            java.awt.Rectangle rec = photo.getBounds();
            Image scaledImage = image.getImage().getScaledInstance(rec.width, rec.height, Image.SCALE_DEFAULT);
            image = new ImageIcon(scaledImage);
            photo.setIcon(image);
            filename = file.getAbsolutePath();

        }

//}
// TODO add your handling code here:
    }//GEN-LAST:event_lB6ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyPressed
        char e = evt.getKeyChar();
        if (e == KeyEvent.VK_BACK_SPACE) {
            if (dob.getText().equals("e.g 27/9/2017")) {
                evt.consume();

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyPressed

    private void dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyReleased
        if (dob.getText().equals("")) {
            dob.setText("e.g 27/9/2017");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyReleased

    private void dobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyTyped
        if (x == 0 || dob.getText().equals("e.g 27/9/2017")) {
            x = 1;
            dob.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyTyped

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void regNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNoActionPerformed

    private void otherNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherNamesActionPerformed

    private void lB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB8ActionPerformed
        String reg = regNo.getText();
        int xp = 1;
        try {
            String sql2 = "SELECT * FROM students ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                String regNo = rs.getString("regNo");
                if (regNo.equalsIgnoreCase(reg)) {
                    theReg = regNo;
                    xp = 3;
                    fName.setText(rs.getString("firstName"));
                    otherNames.setText(rs.getString("otherNames"));
                    fName.setText(rs.getString("firstName"));
                    idNumber.setText(rs.getString("idNumber"));
                    gender.setSelectedItem(rs.getString("gender"));
                    dob.setText(rs.getString("dateOfBirth"));
                    phoneNo.setText(rs.getString("phone"));
                    mail.setText(rs.getString("email"));
                    faculty.setSelectedItem(rs.getString("department"));
                    course.setText(rs.getString("course"));
                    doa.setText(rs.getString("dateofAdmission"));
                    filename = "";
                    byte[] img = rs.getBytes("photo");
                    if (img != null) {
                        ImageIcon image = new ImageIcon(img);
                        Image im = image.getImage();
                        Image myImg = im.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon newImage = new ImageIcon(myImg);
                        photo.setIcon(newImage);
                    } else {
                        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png")));
                    }
                    break;
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e, "Alert", 1);
        }
        if (xp == 1) {
            JOptionPane.showMessageDialog(null, "Student Not Found", "Alert", 1);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lB8ActionPerformed

    private void phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoActionPerformed

    private void phoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyPressed
        char e = evt.getKeyChar();
        if (e == KeyEvent.VK_BACK_SPACE) {
            if (phoneNo.getText().equals("e.g 0705 187 937")) {
                evt.consume();

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoKeyPressed

    private void phoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyReleased

        if (phoneNo.getText().equals("")) {
            phoneNo.setText("e.g 0705 187 937");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoKeyReleased

    private void phoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyTyped

        if (x == 0 || phoneNo.getText().equals("e.g 0705 187 937")) {
            x = 1;
            phoneNo.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoKeyTyped

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyPressed
        char e = evt.getKeyChar();
        if (e == KeyEvent.VK_BACK_SPACE) {
            if (mail.getText().equals("e.g Test@gmail.com")) {
                evt.consume();

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyPressed

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased
        if (mail.getText().equals("")) {
            mail.setText("e.g Test@gmail.com");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyReleased

    private void mailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyTyped

        if (x == 0 || mail.getText().equals("e.g Test@gmail.com")) {
            x = 1;
            mail.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyTyped

    private void doaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doaActionPerformed

    private void doaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doaKeyPressed
        char e = evt.getKeyChar();
        if (e == KeyEvent.VK_BACK_SPACE) {
            if (doa.getText().equals("e.g 27/9/2017")) {
                evt.consume();

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_doaKeyPressed

    private void doaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doaKeyReleased
        if (doa.getText().equals("")) {
            doa.setText("e.g 27/9/2017");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_doaKeyReleased

    private void doaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doaKeyTyped
        if (x == 0 || doa.getText().equals("e.g 27/9/2017")) {
            x = 1;
            doa.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_doaKeyTyped

    private void lB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB9ActionPerformed
        String reg_number = regNo.getText();
        String first_name = fName.getText();
        String other_names = otherNames.getText();
        String id_number = idNumber.getText();
        String genders = (String) gender.getSelectedItem();
        String dobs = dob.getText();
        String phones = phoneNo.getText();
        String mails = mail.getText();
        String department = (String) faculty.getSelectedItem();
        String courses = course.getText();
        String doas = doa.getText();
        if (doas.equals("e.g 27/9/2017") || dobs.equals("e.g 27/9/2017") || mails.equals("e.g Test@gmail.com") || phones.equals("e.g 0705 187 937") || courses.equals("") || reg_number.equals("") || first_name.equals("") || other_names.equals("") || id_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly Flll All Fields", "Alert", 1);
        } else {
            if (!filename.equals("")) {
                try {
                    String sql = "Update students set firstName='" + first_name + "',otherNames='" + other_names + "',regNo='" + reg_number + "',department='" + department + "',course='" + courses + "',gender='" + genders + "',phone='" + phones + "',email='" + mails + "',dateOfBirth='"
                            + dobs + "',idNumber='" + id_number + "',dateofAdmission='" + doas + "',photo=?'" + "' where regNo='" + theReg + "'";
                    pst = con.prepareStatement(sql);
                    InputStream is = new FileInputStream(new File(filename));
                    pst.setBlob(1, is);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Update Succesful", "Alert", 1);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error" + e, "Alert", 1);
                }
            } else {
                try {
                    String sql = "Update students set firstName='" + first_name + "',otherNames='" + other_names + "',regNo='" + reg_number + "',department='" + department + "',course='" + courses + "',gender='" + genders + "',phone='" + phones + "',email='" + mails + "',dateOfBirth='"
                            + dobs + "',idNumber='" + id_number + "',dateofAdmission='" + doas + "' where regNo='" + theReg + "'";
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Update Succesful", "Alert", 1);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error" + e, "Alert", 1);
                }
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lB9ActionPerformed

    private void lB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB10ActionPerformed
        if(!theReg.equals("")){
        int xx = JOptionPane.showConfirmDialog(null, "Are You Sure To Delete", "Alert", 1);
        if (xx == 0) {
            try {
                String sql = "delete from students where regNo='" + theReg + "'";

                pst = con.prepareStatement(sql);
                pst.executeUpdate();
                filename = "";
                photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png")));
                theReg = "";
                regNo.setText("");
                    course.setText("");
                fName.setText("");
                otherNames.setText("");
                idNumber.setText("");
                dob.setText("e.g 27/9/2017");
                doa.setText("e.g 27/9/2017");
                phoneNo.setText("e.g 0705 187 937");
                mail.setText("e.g Test@gmail.com");
                JOptionPane.showMessageDialog(null, "Student Deleted Sucessfuly", "Alert", 1);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error"+e,"Alert",1);
            }
        }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_lB10ActionPerformed

    private void lB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB11ActionPerformed
        String reg_number = regNo.getText();
        String first_name = fName.getText();
        String other_names = otherNames.getText();
        String id_number = idNumber.getText();
        String genders = (String) gender.getSelectedItem();
        String dobs = dob.getText();
        String phones = phoneNo.getText();
        String mails = mail.getText();
        String department = (String) faculty.getSelectedItem();
        String courses = course.getText();
        String doas = doa.getText();
        if (doas.equals("e.g 27/9/2017") || dobs.equals("e.g 27/9/2017") || mails.equals("e.g Test@gmail.com") || phones.equals("e.g 0705 187 937") || courses.equals("") || reg_number.equals("") || first_name.equals("") || other_names.equals("") || id_number.equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly Flll All Fields", "Alert", 1);
        } else {
            if (!filename.equals("")) {
                try {
                    String sql = "INSERT INTO students(firstName,otherNames,regNo,department,course,gender,phone,email,dateOfBirth,idNumber,dateOfAdmission,photo)"
                            + "VALUES('" + first_name + "','" + other_names + "','" + reg_number + "','" + department + "','" + courses + "','" + genders + "','" + phones + "','" + mails + "','"
                            + dobs + "','" + id_number + "','" + doas + "', ?'" + "')";
                    pst = con.prepareStatement(sql);
                    InputStream is = new FileInputStream(new File(filename));
                    pst.setBlob(1, is);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Student Added Succesfully", "Alert", 1);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error" + e, "Alert", 1);
                }
            } else {
                try {
                    String sql = "INSERT INTO students(firstName,otherNames,regNo,department,course,gender,phone,email,dateOfBirth,idNumber,dateOfAdmission)"
                            + "VALUES('" + first_name + "','" + other_names + "','" + reg_number + "','" + department + "','" + courses + "','" + genders + "','" + phones + "','" + mails + "','"
                            + dobs + "','" + id_number + "','" + doas + "')";
                    pst = con.prepareStatement(sql);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Student Added Succesfully", "Alert", 1);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error" + e, "Alert", 1);
                }
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lB11ActionPerformed

    private void lB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB12ActionPerformed
        filename = "";
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png")));
        theReg = "";
        fName.setText("");
        regNo.setText("");
        course.setText("");
        otherNames.setText("");
        idNumber.setText("");
        dob.setText("e.g 27/9/2017");
        doa.setText("e.g 27/9/2017");
        phoneNo.setText("e.g 0705 187 937");
        mail.setText("e.g Test@gmail.com");

        // TODO add your handling code here:
    }//GEN-LAST:event_lB12ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField course;
    private javax.swing.JTextField doa;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField fName;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField idNumber;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lB10;
    private javax.swing.JButton lB11;
    private javax.swing.JButton lB12;
    private javax.swing.JButton lB6;
    private javax.swing.JButton lB8;
    private javax.swing.JButton lB9;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField otherNames;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField regNo;
    private javax.swing.JLabel uL10;
    private javax.swing.JLabel uL11;
    private javax.swing.JLabel uL12;
    private javax.swing.JLabel uL13;
    private javax.swing.JLabel uL14;
    private javax.swing.JLabel uL15;
    private javax.swing.JLabel uL16;
    private javax.swing.JLabel uL17;
    private javax.swing.JLabel uL18;
    private javax.swing.JLabel uL5;
    private javax.swing.JLabel uL8;
    private javax.swing.JLabel uL9;
    // End of variables declaration//GEN-END:variables
}
