/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author G50
 */
public class reception_gene extends javax.swing.JPanel {

    /**
     * Creates new form session_reporting
     */

    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;


    public reception_gene() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        Properties properties = new Properties();
        try {
              InputStream inputStream = reception_gene.class.getResourceAsStream("/store/mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);

        }

        try {
            String dbname = properties.getProperty("db.name");
            String pass = properties.getProperty("db.pass");
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + properties.getProperty("db.host") + ":" + properties.getProperty("db.port") + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);
        } catch (Exception e) {

            System.exit(0);
        }
        
         DefaultTableModel modelx = new DefaultTableModel();
        try {
            modelx = (DefaultTableModel) list_view.getModel();

            String sql2 = "SELECT * FROM students ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            modelx.setRowCount(0);
             int cash = 0;
            while (rs.next()) {
                cash+=1;
                String reg = rs.getString("regNo");
                String name = rs.getString("firstName")+" "+rs.getString("otherNames");
                String gender = rs.getString("gender");
                String dept = rs.getString("department");
                 String course = rs.getString("course");

                modelx.addRow(new Object[]{reg, name, gender, dept, course});

            }
                cush2.setText("" + cash);
           
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        cush2 = new javax.swing.JTextField();
        uL3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        list_view = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cush2.setEditable(false);
        cush2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cush2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(cush2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 200, -1));

        uL3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL3.setText("Students");
        jPanel3.add(uL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 130, 20));

        list_view.setAutoCreateRowSorter(true);
        list_view.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        list_view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reg No", "Names", "Gender", "Department", "Course"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        list_view.setCellSelectionEnabled(true);
        jScrollPane5.setViewportView(list_view);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1040, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cush2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable list_view;
    private javax.swing.JLabel uL3;
    // End of variables declaration//GEN-END:variables
}
