/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author G50
 */
public class reception_session extends javax.swing.JPanel {

    /**
     * Creates new form session_reporting
     */
    int x = 0;
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;
    String theReg;



    public reception_session() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        Properties properties = new Properties();
        try {
              InputStream inputStream = reception_session.class.getResourceAsStream("/store/mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);

        }

        try {
            String dbname = properties.getProperty("db.name");
            String pass = properties.getProperty("db.pass");
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + properties.getProperty("db.host") + ":" + properties.getProperty("db.port") + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);
        } catch (Exception e) {

            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uL11 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        uL12 = new javax.swing.JLabel();
        otherNames = new javax.swing.JTextField();
        uL13 = new javax.swing.JLabel();
        idNumber = new javax.swing.JTextField();
        uL15 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<String>();
        uL14 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        uL5 = new javax.swing.JLabel();
        regNo = new javax.swing.JTextField();
        uL10 = new javax.swing.JLabel();
        lB8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        uL9 = new javax.swing.JLabel();
        phoneNo = new javax.swing.JTextField();
        uL16 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        uL8 = new javax.swing.JLabel();
        uL17 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox<String>();
        course = new javax.swing.JTextField();
        doa = new javax.swing.JTextField();
        uL18 = new javax.swing.JLabel();
        lB11 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "     Doctors Session Manager     ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL11.setText("First Name");
        jPanel2.add(uL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 20));

        fName.setEditable(false);
        fName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        fName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, -1));

        uL12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL12.setText("Other Names");
        jPanel2.add(uL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 20));

        otherNames.setEditable(false);
        otherNames.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        otherNames.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        otherNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherNamesActionPerformed(evt);
            }
        });
        jPanel2.add(otherNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, -1));

        uL13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL13.setText("Id Number");
        jPanel2.add(uL13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 20));

        idNumber.setEditable(false);
        idNumber.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        idNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel2.add(idNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, -1));

        uL15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL15.setText("Gender");
        jPanel2.add(uL15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 20));

        gender.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 250, -1));

        uL14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL14.setText("Date of Birth");
        jPanel2.add(uL14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 20));

        dob.setEditable(false);
        dob.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobKeyTyped(evt);
            }
        });
        jPanel2.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 30));

        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png"))); // NOI18N
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 140, 150));

        uL5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uL5.setText("Passport");
        jPanel2.add(uL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 480, 340));

        regNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        regNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        regNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNoActionPerformed(evt);
            }
        });
        jPanel3.add(regNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, -1));

        uL10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uL10.setText("Registration Number");
        jPanel3.add(uL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 20));

        lB8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB8.setText("Fetch >>>");
        lB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB8ActionPerformed(evt);
            }
        });
        jPanel3.add(lB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 120, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL9.setText("Phone No.");
        jPanel4.add(uL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));

        phoneNo.setEditable(false);
        phoneNo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        phoneNo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoActionPerformed(evt);
            }
        });
        phoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNoKeyTyped(evt);
            }
        });
        jPanel4.add(phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 320, 30));

        uL16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL16.setText("Mail");
        jPanel4.add(uL16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, -1));

        mail.setEditable(false);
        mail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mailKeyTyped(evt);
            }
        });
        jPanel4.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 320, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 480, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 18))); // NOI18N
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uL8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL8.setText("Course");
        jPanel5.add(uL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        uL17.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL17.setText("Faculty/School");
        jPanel5.add(uL17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        faculty.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        faculty.setMaximumRowCount(4);
        faculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School of Business & Economics", "Agriculture & Natural Resource Management", "Information Science & Technology", "School of Law", "Education & Human Resource Dev.", "Health Sciences", "Faculty of Pure and Applied Sciences", "Arts & Social Sciences" }));
        jPanel5.add(faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 340, 30));

        course.setEditable(false);
        course.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        course.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 340, -1));

        doa.setEditable(false);
        doa.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        doa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        doa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doaActionPerformed(evt);
            }
        });
        doa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                doaKeyTyped(evt);
            }
        });
        jPanel5.add(doa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 340, 30));

        uL18.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        uL18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uL18.setText("Admission Date");
        jPanel5.add(uL18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 510, 190));

        lB11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lB11.setText("CREATE SESSION");
        lB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lB11ActionPerformed(evt);
            }
        });
        jPanel3.add(lB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB11ActionPerformed

        if (!theReg.equals("")) {
            try {
                String sql = "INSERT INTO doctor_session(regNo)"
                        + "VALUES('" + theReg + "')";
                pst = con.prepareStatement(sql);

                pst.executeUpdate();
                photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png")));
                theReg = "";
                fName.setText("");
                regNo.setText("");
                course.setText("");
                otherNames.setText("");
                idNumber.setText("");
                dob.setText("");
                doa.setText("");
                phoneNo.setText("");
                mail.setText("");
                JOptionPane.showMessageDialog(null, "Session Created Succesfully", "Alert", 1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error" + e, "Alert", 1);
            }
        } else {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lB11ActionPerformed

    private void doaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doaKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_doaKeyTyped

    private void doaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doaKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_doaKeyReleased

    private void doaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doaKeyPressed

        //}     // TODO add your handling code here:
    }//GEN-LAST:event_doaKeyPressed

    private void doaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doaActionPerformed

    private void mailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyTyped

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyReleased

    private void mailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_mailKeyPressed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void phoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoKeyTyped

    private void phoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoKeyReleased

    private void phoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNoKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoKeyPressed

    private void phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoActionPerformed

    private void lB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lB8ActionPerformed
        String reg = regNo.getText();
        int xp = 1;
        try {
            String sql2 = "SELECT * FROM students ";
            st = con.createStatement();
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                String regNo = rs.getString("regNo");
                if (regNo.equalsIgnoreCase(reg)) {
                    theReg = regNo;
                    xp = 3;
                    fName.setText(rs.getString("firstName"));
                    otherNames.setText(rs.getString("otherNames"));
                    fName.setText(rs.getString("firstName"));
                    idNumber.setText(rs.getString("idNumber"));
                    gender.setSelectedItem(rs.getString("gender"));
                    dob.setText(rs.getString("dateOfBirth"));
                    phoneNo.setText(rs.getString("phone"));
                    mail.setText(rs.getString("email"));
                    faculty.setSelectedItem(rs.getString("department"));
                    course.setText(rs.getString("course"));
                    doa.setText(rs.getString("dateofAdmission"));
                    byte[] img = rs.getBytes("photo");
                    if (img != null) {
                        ImageIcon image = new ImageIcon(img);
                        Image im = image.getImage();
                        Image myImg = im.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon newImage = new ImageIcon(myImg);
                        photo.setIcon(newImage);
                    } else {
                        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/avatar - Copy.png")));
                    }
                    break;
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e, "Alert", 1);
        }
        if (xp == 1) {
            JOptionPane.showMessageDialog(null, "Student Not Found", "Alert", 1);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_lB8ActionPerformed

    private void regNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNoActionPerformed

    private void dobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyTyped

    private void dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyReleased

    private void dobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyPressed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void otherNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherNamesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherNamesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField course;
    private javax.swing.JTextField doa;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField fName;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField idNumber;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lB11;
    private javax.swing.JButton lB8;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField otherNames;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField regNo;
    private javax.swing.JLabel uL10;
    private javax.swing.JLabel uL11;
    private javax.swing.JLabel uL12;
    private javax.swing.JLabel uL13;
    private javax.swing.JLabel uL14;
    private javax.swing.JLabel uL15;
    private javax.swing.JLabel uL16;
    private javax.swing.JLabel uL17;
    private javax.swing.JLabel uL18;
    private javax.swing.JLabel uL5;
    private javax.swing.JLabel uL8;
    private javax.swing.JLabel uL9;
    // End of variables declaration//GEN-END:variables
}
