/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author G50
 */
public class splashMenu extends javax.swing.JFrame {

    /**
     * Creates new form animeFrame
     */
    Connection con = null;
    ResultSet rs;
    Statement st;
    PreparedStatement pst = null;

    public splashMenu() {
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.messageFont", new FontUIResource(new Font("Trebuchet MS", 1, 15)));
        UI.put("OptionPane.background", new ColorUIResource(255, 255, 255));
        UI.put("Panel.background", new ColorUIResource(255, 255, 255));
        d1.setVisible(false);
        d11.setVisible(false);
        d2.setVisible(false);
        d22.setVisible(false);
        d3.setVisible(false);
        d33.setVisible(false);
        d4.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        d4 = new javax.swing.JButton();
        d3 = new javax.swing.JTextField();
        d33 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        d22 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        d11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(620, 350));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setBackground(java.awt.SystemColor.controlDkShadow);
        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d4.setText("Configure");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 210, 31));

        d3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 211, 30));

        d33.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d33.setText("dbPassW");
        jLayeredPane1.add(d33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 70, -1));

        d2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 211, 30));

        d22.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d22.setText("dbPort");
        jLayeredPane1.add(d22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, -1));

        d1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 211, 30));

        d11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        d11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        d11.setText("dbHost");
        jLayeredPane1.add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store/splash.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        Properties properties = new Properties();
        try {
              InputStream inputStream = splashMenu.class.getResourceAsStream("/store/mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);
            System.exit(0);
        }

        try {
            String dbname = properties.getProperty("db.name");
            String pass = properties.getProperty("db.pass");
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + properties.getProperty("db.host") + ":" + properties.getProperty("db.port") + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);
            logIn bob = new logIn();

            splashMenu.this.dispose();
            bob.setVisible(true);

        } catch (Exception e) {
            String[] options = {"Configure", "Exit"};
            int x = JOptionPane.showOptionDialog(null, "Medical Information Mangement System is not configured\nDatabase connection failed",
                    "Alert",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
            if (x == 0) {
                d1.setVisible(true);
                d11.setVisible(true);
                d2.setVisible(true);
                d22.setVisible(true);
                d3.setVisible(true);
                d33.setVisible(true);
                d4.setVisible(true);
                d1.setText(properties.getProperty("db.host"));
                d2.setText(properties.getProperty("db.port"));
                d3.setText(properties.getProperty("db.pass"));
            } else {
                System.exit(0);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d3ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        Properties properties = new Properties();
        try {
            InputStream inputStream = new FileInputStream("mrm.properties");
            properties.load(inputStream);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while reading the properties file", "Alert", 1);

        }
        try {
            String dbname = properties.getProperty("db.name");
            String pass = d3.getText();
            String username = properties.getProperty("db.user");
            String Url = "jdbc:mysql://" + d1.getText() + ":" + d2.getText() + "/";
            String Drivers = "com.mysql.jdbc.Driver";
            Class.forName(Drivers);
            con = DriverManager.getConnection(Url + dbname, username, pass);

            Properties prop = new Properties();
            OutputStream output = null;

            try {

                output = new FileOutputStream("mrm.properties");

                // set the properties value
                prop.setProperty("db.name", "mims_db");
                prop.setProperty("db.user", "root");
                prop.setProperty("db.host", d1.getText());
                prop.setProperty("db.port", d2.getText());
                prop.setProperty("db.pass", d3.getText());

                // save properties to project root folder
                prop.store(output, null);
  

            } catch (IOException io) {
                JOptionPane.showMessageDialog(null, "error" + io, "Alert", 1);
                io.printStackTrace();
            } finally {
                if (output != null) {
                    try {
                        output.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }

            }
            logIn bob = new logIn();

            splashMenu.this.dispose();
            bob.setVisible(true);

        } catch (Exception e) {
            String[] options = {"Configure", "Exit"};
            int x = JOptionPane.showOptionDialog(null, "Configuration Details Incorrect\nDatabase connection failed",
                    "Alert",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
            if (x == 0) {

            } else {
                System.exit(0);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_d4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashMenu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d1;
    private javax.swing.JLabel d11;
    private javax.swing.JTextField d2;
    private javax.swing.JLabel d22;
    private javax.swing.JTextField d3;
    private javax.swing.JLabel d33;
    private javax.swing.JButton d4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
